[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48011
Protocol = 'http'
MaxResultCount = 50000
StartupMsg = 'This is the Gateway Adapter Microservice'
Timeout = 5000

[Logging]
EnableRemote = false
File = './logs/gateway-adapter.log'

[Clients]
  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'gateway-adapter'
  Password = ''
  Port = 27017
  Username = ''
  Timeout = 5000
  Type = 'mongodb'

[MQTT]
Address = '119.3.36.199'
Port = 3002
Protocol = 'TCP'
Publisher = 'gateway-adapter-go'
User = 'admin'
Password = 'mingdu2018'

[Hardware]
File = '/mnt/host/hardware.json'